spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive
    username: postgres
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5432/reactive
    user: postgres
    password: root