
grpc:
  server:
    port: 9098

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ca_pss_v1
    username: postgres
    password: postgres
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true