// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientService.proto

package com.ca.patient;

/**
 * Protobuf type {@code com.ca.patient.Address}
 */
public final class Address extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ca.patient.Address)
    AddressOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Address.newBuilder() to construct.
  private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Address() {
    appointmentDateTime_ = "";
    appointmentCreationDateTime_ = "";
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Address();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ca.patient.PatientServiceOuterClass.internal_static_com_ca_patient_Address_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ca.patient.PatientServiceOuterClass.internal_static_com_ca_patient_Address_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ca.patient.Address.class, com.ca.patient.Address.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int PATIENTID_FIELD_NUMBER = 2;
  private com.ca.patient.PatientInfo patientId_;
  /**
   * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
   * @return Whether the patientId field is set.
   */
  @java.lang.Override
  public boolean hasPatientId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
   * @return The patientId.
   */
  @java.lang.Override
  public com.ca.patient.PatientInfo getPatientId() {
    return patientId_ == null ? com.ca.patient.PatientInfo.getDefaultInstance() : patientId_;
  }
  /**
   * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
   */
  @java.lang.Override
  public com.ca.patient.PatientInfoOrBuilder getPatientIdOrBuilder() {
    return patientId_ == null ? com.ca.patient.PatientInfo.getDefaultInstance() : patientId_;
  }

  public static final int PRACTICEID_FIELD_NUMBER = 3;
  private com.ca.patient.PracticeInfo practiceId_;
  /**
   * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
   * @return Whether the practiceId field is set.
   */
  @java.lang.Override
  public boolean hasPracticeId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
   * @return The practiceId.
   */
  @java.lang.Override
  public com.ca.patient.PracticeInfo getPracticeId() {
    return practiceId_ == null ? com.ca.patient.PracticeInfo.getDefaultInstance() : practiceId_;
  }
  /**
   * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
   */
  @java.lang.Override
  public com.ca.patient.PracticeInfoOrBuilder getPracticeIdOrBuilder() {
    return practiceId_ == null ? com.ca.patient.PracticeInfo.getDefaultInstance() : practiceId_;
  }

  public static final int APPOINTMENTDATETIME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appointmentDateTime_ = "";
  /**
   * <code>string appointmentDateTime = 4;</code>
   * @return The appointmentDateTime.
   */
  @java.lang.Override
  public java.lang.String getAppointmentDateTime() {
    java.lang.Object ref = appointmentDateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appointmentDateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string appointmentDateTime = 4;</code>
   * @return The bytes for appointmentDateTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppointmentDateTimeBytes() {
    java.lang.Object ref = appointmentDateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appointmentDateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPOINTMENTCREATIONDATETIME_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appointmentCreationDateTime_ = "";
  /**
   * <code>string appointmentCreationDateTime = 5;</code>
   * @return The appointmentCreationDateTime.
   */
  @java.lang.Override
  public java.lang.String getAppointmentCreationDateTime() {
    java.lang.Object ref = appointmentCreationDateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appointmentCreationDateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string appointmentCreationDateTime = 5;</code>
   * @return The bytes for appointmentCreationDateTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppointmentCreationDateTimeBytes() {
    java.lang.Object ref = appointmentCreationDateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appointmentCreationDateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPatientId());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getPracticeId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appointmentDateTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appointmentDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appointmentCreationDateTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, appointmentCreationDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPatientId());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPracticeId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appointmentDateTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appointmentDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appointmentCreationDateTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, appointmentCreationDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ca.patient.Address)) {
      return super.equals(obj);
    }
    com.ca.patient.Address other = (com.ca.patient.Address) obj;

    if (getId()
        != other.getId()) return false;
    if (hasPatientId() != other.hasPatientId()) return false;
    if (hasPatientId()) {
      if (!getPatientId()
          .equals(other.getPatientId())) return false;
    }
    if (hasPracticeId() != other.hasPracticeId()) return false;
    if (hasPracticeId()) {
      if (!getPracticeId()
          .equals(other.getPracticeId())) return false;
    }
    if (!getAppointmentDateTime()
        .equals(other.getAppointmentDateTime())) return false;
    if (!getAppointmentCreationDateTime()
        .equals(other.getAppointmentCreationDateTime())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasPatientId()) {
      hash = (37 * hash) + PATIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getPatientId().hashCode();
    }
    if (hasPracticeId()) {
      hash = (37 * hash) + PRACTICEID_FIELD_NUMBER;
      hash = (53 * hash) + getPracticeId().hashCode();
    }
    hash = (37 * hash) + APPOINTMENTDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getAppointmentDateTime().hashCode();
    hash = (37 * hash) + APPOINTMENTCREATIONDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getAppointmentCreationDateTime().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ca.patient.Address parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ca.patient.Address parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ca.patient.Address parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ca.patient.Address parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ca.patient.Address parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ca.patient.Address parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ca.patient.Address parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ca.patient.Address parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ca.patient.Address parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ca.patient.Address parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ca.patient.Address parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ca.patient.Address parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ca.patient.Address prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ca.patient.Address}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ca.patient.Address)
      com.ca.patient.AddressOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ca.patient.PatientServiceOuterClass.internal_static_com_ca_patient_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ca.patient.PatientServiceOuterClass.internal_static_com_ca_patient_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ca.patient.Address.class, com.ca.patient.Address.Builder.class);
    }

    // Construct using com.ca.patient.Address.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPatientIdFieldBuilder();
        getPracticeIdFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      patientId_ = null;
      if (patientIdBuilder_ != null) {
        patientIdBuilder_.dispose();
        patientIdBuilder_ = null;
      }
      practiceId_ = null;
      if (practiceIdBuilder_ != null) {
        practiceIdBuilder_.dispose();
        practiceIdBuilder_ = null;
      }
      appointmentDateTime_ = "";
      appointmentCreationDateTime_ = "";
      status_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ca.patient.PatientServiceOuterClass.internal_static_com_ca_patient_Address_descriptor;
    }

    @java.lang.Override
    public com.ca.patient.Address getDefaultInstanceForType() {
      return com.ca.patient.Address.getDefaultInstance();
    }

    @java.lang.Override
    public com.ca.patient.Address build() {
      com.ca.patient.Address result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ca.patient.Address buildPartial() {
      com.ca.patient.Address result = new com.ca.patient.Address(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ca.patient.Address result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.patientId_ = patientIdBuilder_ == null
            ? patientId_
            : patientIdBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.practiceId_ = practiceIdBuilder_ == null
            ? practiceId_
            : practiceIdBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.appointmentDateTime_ = appointmentDateTime_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.appointmentCreationDateTime_ = appointmentCreationDateTime_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.status_ = status_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ca.patient.Address) {
        return mergeFrom((com.ca.patient.Address)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ca.patient.Address other) {
      if (other == com.ca.patient.Address.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasPatientId()) {
        mergePatientId(other.getPatientId());
      }
      if (other.hasPracticeId()) {
        mergePracticeId(other.getPracticeId());
      }
      if (!other.getAppointmentDateTime().isEmpty()) {
        appointmentDateTime_ = other.appointmentDateTime_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getAppointmentCreationDateTime().isEmpty()) {
        appointmentCreationDateTime_ = other.appointmentCreationDateTime_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getPatientIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getPracticeIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              appointmentDateTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              appointmentCreationDateTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private com.ca.patient.PatientInfo patientId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ca.patient.PatientInfo, com.ca.patient.PatientInfo.Builder, com.ca.patient.PatientInfoOrBuilder> patientIdBuilder_;
    /**
     * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
     * @return Whether the patientId field is set.
     */
    public boolean hasPatientId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
     * @return The patientId.
     */
    public com.ca.patient.PatientInfo getPatientId() {
      if (patientIdBuilder_ == null) {
        return patientId_ == null ? com.ca.patient.PatientInfo.getDefaultInstance() : patientId_;
      } else {
        return patientIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
     */
    public Builder setPatientId(com.ca.patient.PatientInfo value) {
      if (patientIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        patientId_ = value;
      } else {
        patientIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
     */
    public Builder setPatientId(
        com.ca.patient.PatientInfo.Builder builderForValue) {
      if (patientIdBuilder_ == null) {
        patientId_ = builderForValue.build();
      } else {
        patientIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
     */
    public Builder mergePatientId(com.ca.patient.PatientInfo value) {
      if (patientIdBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          patientId_ != null &&
          patientId_ != com.ca.patient.PatientInfo.getDefaultInstance()) {
          getPatientIdBuilder().mergeFrom(value);
        } else {
          patientId_ = value;
        }
      } else {
        patientIdBuilder_.mergeFrom(value);
      }
      if (patientId_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
     */
    public Builder clearPatientId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      patientId_ = null;
      if (patientIdBuilder_ != null) {
        patientIdBuilder_.dispose();
        patientIdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
     */
    public com.ca.patient.PatientInfo.Builder getPatientIdBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPatientIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
     */
    public com.ca.patient.PatientInfoOrBuilder getPatientIdOrBuilder() {
      if (patientIdBuilder_ != null) {
        return patientIdBuilder_.getMessageOrBuilder();
      } else {
        return patientId_ == null ?
            com.ca.patient.PatientInfo.getDefaultInstance() : patientId_;
      }
    }
    /**
     * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ca.patient.PatientInfo, com.ca.patient.PatientInfo.Builder, com.ca.patient.PatientInfoOrBuilder> 
        getPatientIdFieldBuilder() {
      if (patientIdBuilder_ == null) {
        patientIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ca.patient.PatientInfo, com.ca.patient.PatientInfo.Builder, com.ca.patient.PatientInfoOrBuilder>(
                getPatientId(),
                getParentForChildren(),
                isClean());
        patientId_ = null;
      }
      return patientIdBuilder_;
    }

    private com.ca.patient.PracticeInfo practiceId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ca.patient.PracticeInfo, com.ca.patient.PracticeInfo.Builder, com.ca.patient.PracticeInfoOrBuilder> practiceIdBuilder_;
    /**
     * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
     * @return Whether the practiceId field is set.
     */
    public boolean hasPracticeId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
     * @return The practiceId.
     */
    public com.ca.patient.PracticeInfo getPracticeId() {
      if (practiceIdBuilder_ == null) {
        return practiceId_ == null ? com.ca.patient.PracticeInfo.getDefaultInstance() : practiceId_;
      } else {
        return practiceIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
     */
    public Builder setPracticeId(com.ca.patient.PracticeInfo value) {
      if (practiceIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        practiceId_ = value;
      } else {
        practiceIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
     */
    public Builder setPracticeId(
        com.ca.patient.PracticeInfo.Builder builderForValue) {
      if (practiceIdBuilder_ == null) {
        practiceId_ = builderForValue.build();
      } else {
        practiceIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
     */
    public Builder mergePracticeId(com.ca.patient.PracticeInfo value) {
      if (practiceIdBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          practiceId_ != null &&
          practiceId_ != com.ca.patient.PracticeInfo.getDefaultInstance()) {
          getPracticeIdBuilder().mergeFrom(value);
        } else {
          practiceId_ = value;
        }
      } else {
        practiceIdBuilder_.mergeFrom(value);
      }
      if (practiceId_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
     */
    public Builder clearPracticeId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      practiceId_ = null;
      if (practiceIdBuilder_ != null) {
        practiceIdBuilder_.dispose();
        practiceIdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
     */
    public com.ca.patient.PracticeInfo.Builder getPracticeIdBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPracticeIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
     */
    public com.ca.patient.PracticeInfoOrBuilder getPracticeIdOrBuilder() {
      if (practiceIdBuilder_ != null) {
        return practiceIdBuilder_.getMessageOrBuilder();
      } else {
        return practiceId_ == null ?
            com.ca.patient.PracticeInfo.getDefaultInstance() : practiceId_;
      }
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ca.patient.PracticeInfo, com.ca.patient.PracticeInfo.Builder, com.ca.patient.PracticeInfoOrBuilder> 
        getPracticeIdFieldBuilder() {
      if (practiceIdBuilder_ == null) {
        practiceIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ca.patient.PracticeInfo, com.ca.patient.PracticeInfo.Builder, com.ca.patient.PracticeInfoOrBuilder>(
                getPracticeId(),
                getParentForChildren(),
                isClean());
        practiceId_ = null;
      }
      return practiceIdBuilder_;
    }

    private java.lang.Object appointmentDateTime_ = "";
    /**
     * <code>string appointmentDateTime = 4;</code>
     * @return The appointmentDateTime.
     */
    public java.lang.String getAppointmentDateTime() {
      java.lang.Object ref = appointmentDateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appointmentDateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appointmentDateTime = 4;</code>
     * @return The bytes for appointmentDateTime.
     */
    public com.google.protobuf.ByteString
        getAppointmentDateTimeBytes() {
      java.lang.Object ref = appointmentDateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appointmentDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appointmentDateTime = 4;</code>
     * @param value The appointmentDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setAppointmentDateTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appointmentDateTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string appointmentDateTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppointmentDateTime() {
      appointmentDateTime_ = getDefaultInstance().getAppointmentDateTime();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string appointmentDateTime = 4;</code>
     * @param value The bytes for appointmentDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setAppointmentDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appointmentDateTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object appointmentCreationDateTime_ = "";
    /**
     * <code>string appointmentCreationDateTime = 5;</code>
     * @return The appointmentCreationDateTime.
     */
    public java.lang.String getAppointmentCreationDateTime() {
      java.lang.Object ref = appointmentCreationDateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appointmentCreationDateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appointmentCreationDateTime = 5;</code>
     * @return The bytes for appointmentCreationDateTime.
     */
    public com.google.protobuf.ByteString
        getAppointmentCreationDateTimeBytes() {
      java.lang.Object ref = appointmentCreationDateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appointmentCreationDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appointmentCreationDateTime = 5;</code>
     * @param value The appointmentCreationDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setAppointmentCreationDateTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appointmentCreationDateTime_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string appointmentCreationDateTime = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppointmentCreationDateTime() {
      appointmentCreationDateTime_ = getDefaultInstance().getAppointmentCreationDateTime();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string appointmentCreationDateTime = 5;</code>
     * @param value The bytes for appointmentCreationDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setAppointmentCreationDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appointmentCreationDateTime_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 6;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 6;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 6;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ca.patient.Address)
  }

  // @@protoc_insertion_point(class_scope:com.ca.patient.Address)
  private static final com.ca.patient.Address DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ca.patient.Address();
  }

  public static com.ca.patient.Address getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Address>
      PARSER = new com.google.protobuf.AbstractParser<Address>() {
    @java.lang.Override
    public Address parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Address> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Address> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ca.patient.Address getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

