// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientService.proto

package com.ca.patient;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ca.patient.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
   * @return Whether the patientId field is set.
   */
  boolean hasPatientId();
  /**
   * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
   * @return The patientId.
   */
  com.ca.patient.PatientInfo getPatientId();
  /**
   * <code>.com.ca.patient.PatientInfo patientId = 2;</code>
   */
  com.ca.patient.PatientInfoOrBuilder getPatientIdOrBuilder();

  /**
   * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
   * @return Whether the practiceId field is set.
   */
  boolean hasPracticeId();
  /**
   * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
   * @return The practiceId.
   */
  com.ca.patient.PracticeInfo getPracticeId();
  /**
   * <code>.com.ca.patient.PracticeInfo practiceId = 3;</code>
   */
  com.ca.patient.PracticeInfoOrBuilder getPracticeIdOrBuilder();

  /**
   * <code>string appointmentDateTime = 4;</code>
   * @return The appointmentDateTime.
   */
  java.lang.String getAppointmentDateTime();
  /**
   * <code>string appointmentDateTime = 4;</code>
   * @return The bytes for appointmentDateTime.
   */
  com.google.protobuf.ByteString
      getAppointmentDateTimeBytes();

  /**
   * <code>string appointmentCreationDateTime = 5;</code>
   * @return The appointmentCreationDateTime.
   */
  java.lang.String getAppointmentCreationDateTime();
  /**
   * <code>string appointmentCreationDateTime = 5;</code>
   * @return The bytes for appointmentCreationDateTime.
   */
  com.google.protobuf.ByteString
      getAppointmentCreationDateTimeBytes();

  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
