// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientService.proto

package com.ca.patient;

public interface AppointmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ca.patient.Appointment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 appointmentId = 1;</code>
   * @return The appointmentId.
   */
  long getAppointmentId();

  /**
   * <code>.com.ca.patient.PatientInfo patient = 2;</code>
   * @return Whether the patient field is set.
   */
  boolean hasPatient();
  /**
   * <code>.com.ca.patient.PatientInfo patient = 2;</code>
   * @return The patient.
   */
  com.ca.patient.PatientInfo getPatient();
  /**
   * <code>.com.ca.patient.PatientInfo patient = 2;</code>
   */
  com.ca.patient.PatientInfoOrBuilder getPatientOrBuilder();

  /**
   * <code>.com.ca.patient.PracticeInfo practice = 3;</code>
   * @return Whether the practice field is set.
   */
  boolean hasPractice();
  /**
   * <code>.com.ca.patient.PracticeInfo practice = 3;</code>
   * @return The practice.
   */
  com.ca.patient.PracticeInfo getPractice();
  /**
   * <code>.com.ca.patient.PracticeInfo practice = 3;</code>
   */
  com.ca.patient.PracticeInfoOrBuilder getPracticeOrBuilder();

  /**
   * <code>string appointmentDateTime = 4;</code>
   * @return The appointmentDateTime.
   */
  java.lang.String getAppointmentDateTime();
  /**
   * <code>string appointmentDateTime = 4;</code>
   * @return The bytes for appointmentDateTime.
   */
  com.google.protobuf.ByteString
      getAppointmentDateTimeBytes();

  /**
   * <code>string appointmentCreationDateTime = 5;</code>
   * @return The appointmentCreationDateTime.
   */
  java.lang.String getAppointmentCreationDateTime();
  /**
   * <code>string appointmentCreationDateTime = 5;</code>
   * @return The bytes for appointmentCreationDateTime.
   */
  com.google.protobuf.ByteString
      getAppointmentCreationDateTimeBytes();

  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
