// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientService.proto

package com.ca.patient;

/**
 * Protobuf type {@code com.ca.patient.CreateAppointmentRequest}
 */
public final class CreateAppointmentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ca.patient.CreateAppointmentRequest)
    CreateAppointmentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateAppointmentRequest.newBuilder() to construct.
  private CreateAppointmentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateAppointmentRequest() {
    appointmentDateTime_ = "";
    appointmentCreationDateTime_ = "";
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateAppointmentRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ca.patient.PatientServiceOuterClass.internal_static_com_ca_patient_CreateAppointmentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ca.patient.PatientServiceOuterClass.internal_static_com_ca_patient_CreateAppointmentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ca.patient.CreateAppointmentRequest.class, com.ca.patient.CreateAppointmentRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PATIENT_FIELD_NUMBER = 1;
  private com.ca.patient.PatientInfo patient_;
  /**
   * <code>.com.ca.patient.PatientInfo patient = 1;</code>
   * @return Whether the patient field is set.
   */
  @java.lang.Override
  public boolean hasPatient() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.ca.patient.PatientInfo patient = 1;</code>
   * @return The patient.
   */
  @java.lang.Override
  public com.ca.patient.PatientInfo getPatient() {
    return patient_ == null ? com.ca.patient.PatientInfo.getDefaultInstance() : patient_;
  }
  /**
   * <code>.com.ca.patient.PatientInfo patient = 1;</code>
   */
  @java.lang.Override
  public com.ca.patient.PatientInfoOrBuilder getPatientOrBuilder() {
    return patient_ == null ? com.ca.patient.PatientInfo.getDefaultInstance() : patient_;
  }

  public static final int PRACTICE_FIELD_NUMBER = 2;
  private com.ca.patient.PracticeInfo practice_;
  /**
   * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
   * @return Whether the practice field is set.
   */
  @java.lang.Override
  public boolean hasPractice() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
   * @return The practice.
   */
  @java.lang.Override
  public com.ca.patient.PracticeInfo getPractice() {
    return practice_ == null ? com.ca.patient.PracticeInfo.getDefaultInstance() : practice_;
  }
  /**
   * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
   */
  @java.lang.Override
  public com.ca.patient.PracticeInfoOrBuilder getPracticeOrBuilder() {
    return practice_ == null ? com.ca.patient.PracticeInfo.getDefaultInstance() : practice_;
  }

  public static final int APPOINTMENTDATETIME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appointmentDateTime_ = "";
  /**
   * <code>string appointmentDateTime = 3;</code>
   * @return The appointmentDateTime.
   */
  @java.lang.Override
  public java.lang.String getAppointmentDateTime() {
    java.lang.Object ref = appointmentDateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appointmentDateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string appointmentDateTime = 3;</code>
   * @return The bytes for appointmentDateTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppointmentDateTimeBytes() {
    java.lang.Object ref = appointmentDateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appointmentDateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPOINTMENTCREATIONDATETIME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appointmentCreationDateTime_ = "";
  /**
   * <code>string appointmentCreationDateTime = 4;</code>
   * @return The appointmentCreationDateTime.
   */
  @java.lang.Override
  public java.lang.String getAppointmentCreationDateTime() {
    java.lang.Object ref = appointmentCreationDateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appointmentCreationDateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string appointmentCreationDateTime = 4;</code>
   * @return The bytes for appointmentCreationDateTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppointmentCreationDateTimeBytes() {
    java.lang.Object ref = appointmentCreationDateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appointmentCreationDateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getPatient());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getPractice());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appointmentDateTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appointmentDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appointmentCreationDateTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appointmentCreationDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPatient());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPractice());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appointmentDateTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appointmentDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appointmentCreationDateTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appointmentCreationDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ca.patient.CreateAppointmentRequest)) {
      return super.equals(obj);
    }
    com.ca.patient.CreateAppointmentRequest other = (com.ca.patient.CreateAppointmentRequest) obj;

    if (hasPatient() != other.hasPatient()) return false;
    if (hasPatient()) {
      if (!getPatient()
          .equals(other.getPatient())) return false;
    }
    if (hasPractice() != other.hasPractice()) return false;
    if (hasPractice()) {
      if (!getPractice()
          .equals(other.getPractice())) return false;
    }
    if (!getAppointmentDateTime()
        .equals(other.getAppointmentDateTime())) return false;
    if (!getAppointmentCreationDateTime()
        .equals(other.getAppointmentCreationDateTime())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPatient()) {
      hash = (37 * hash) + PATIENT_FIELD_NUMBER;
      hash = (53 * hash) + getPatient().hashCode();
    }
    if (hasPractice()) {
      hash = (37 * hash) + PRACTICE_FIELD_NUMBER;
      hash = (53 * hash) + getPractice().hashCode();
    }
    hash = (37 * hash) + APPOINTMENTDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getAppointmentDateTime().hashCode();
    hash = (37 * hash) + APPOINTMENTCREATIONDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getAppointmentCreationDateTime().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ca.patient.CreateAppointmentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ca.patient.CreateAppointmentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ca.patient.CreateAppointmentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ca.patient.CreateAppointmentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ca.patient.CreateAppointmentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ca.patient.CreateAppointmentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ca.patient.CreateAppointmentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ca.patient.CreateAppointmentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ca.patient.CreateAppointmentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ca.patient.CreateAppointmentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ca.patient.CreateAppointmentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ca.patient.CreateAppointmentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ca.patient.CreateAppointmentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ca.patient.CreateAppointmentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ca.patient.CreateAppointmentRequest)
      com.ca.patient.CreateAppointmentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ca.patient.PatientServiceOuterClass.internal_static_com_ca_patient_CreateAppointmentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ca.patient.PatientServiceOuterClass.internal_static_com_ca_patient_CreateAppointmentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ca.patient.CreateAppointmentRequest.class, com.ca.patient.CreateAppointmentRequest.Builder.class);
    }

    // Construct using com.ca.patient.CreateAppointmentRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPatientFieldBuilder();
        getPracticeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      patient_ = null;
      if (patientBuilder_ != null) {
        patientBuilder_.dispose();
        patientBuilder_ = null;
      }
      practice_ = null;
      if (practiceBuilder_ != null) {
        practiceBuilder_.dispose();
        practiceBuilder_ = null;
      }
      appointmentDateTime_ = "";
      appointmentCreationDateTime_ = "";
      status_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ca.patient.PatientServiceOuterClass.internal_static_com_ca_patient_CreateAppointmentRequest_descriptor;
    }

    @java.lang.Override
    public com.ca.patient.CreateAppointmentRequest getDefaultInstanceForType() {
      return com.ca.patient.CreateAppointmentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ca.patient.CreateAppointmentRequest build() {
      com.ca.patient.CreateAppointmentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ca.patient.CreateAppointmentRequest buildPartial() {
      com.ca.patient.CreateAppointmentRequest result = new com.ca.patient.CreateAppointmentRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ca.patient.CreateAppointmentRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.patient_ = patientBuilder_ == null
            ? patient_
            : patientBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.practice_ = practiceBuilder_ == null
            ? practice_
            : practiceBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.appointmentDateTime_ = appointmentDateTime_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.appointmentCreationDateTime_ = appointmentCreationDateTime_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ca.patient.CreateAppointmentRequest) {
        return mergeFrom((com.ca.patient.CreateAppointmentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ca.patient.CreateAppointmentRequest other) {
      if (other == com.ca.patient.CreateAppointmentRequest.getDefaultInstance()) return this;
      if (other.hasPatient()) {
        mergePatient(other.getPatient());
      }
      if (other.hasPractice()) {
        mergePractice(other.getPractice());
      }
      if (!other.getAppointmentDateTime().isEmpty()) {
        appointmentDateTime_ = other.appointmentDateTime_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAppointmentCreationDateTime().isEmpty()) {
        appointmentCreationDateTime_ = other.appointmentCreationDateTime_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPatientFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPracticeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              appointmentDateTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              appointmentCreationDateTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.ca.patient.PatientInfo patient_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ca.patient.PatientInfo, com.ca.patient.PatientInfo.Builder, com.ca.patient.PatientInfoOrBuilder> patientBuilder_;
    /**
     * <code>.com.ca.patient.PatientInfo patient = 1;</code>
     * @return Whether the patient field is set.
     */
    public boolean hasPatient() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.ca.patient.PatientInfo patient = 1;</code>
     * @return The patient.
     */
    public com.ca.patient.PatientInfo getPatient() {
      if (patientBuilder_ == null) {
        return patient_ == null ? com.ca.patient.PatientInfo.getDefaultInstance() : patient_;
      } else {
        return patientBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.ca.patient.PatientInfo patient = 1;</code>
     */
    public Builder setPatient(com.ca.patient.PatientInfo value) {
      if (patientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        patient_ = value;
      } else {
        patientBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PatientInfo patient = 1;</code>
     */
    public Builder setPatient(
        com.ca.patient.PatientInfo.Builder builderForValue) {
      if (patientBuilder_ == null) {
        patient_ = builderForValue.build();
      } else {
        patientBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PatientInfo patient = 1;</code>
     */
    public Builder mergePatient(com.ca.patient.PatientInfo value) {
      if (patientBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          patient_ != null &&
          patient_ != com.ca.patient.PatientInfo.getDefaultInstance()) {
          getPatientBuilder().mergeFrom(value);
        } else {
          patient_ = value;
        }
      } else {
        patientBuilder_.mergeFrom(value);
      }
      if (patient_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.ca.patient.PatientInfo patient = 1;</code>
     */
    public Builder clearPatient() {
      bitField0_ = (bitField0_ & ~0x00000001);
      patient_ = null;
      if (patientBuilder_ != null) {
        patientBuilder_.dispose();
        patientBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PatientInfo patient = 1;</code>
     */
    public com.ca.patient.PatientInfo.Builder getPatientBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPatientFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.ca.patient.PatientInfo patient = 1;</code>
     */
    public com.ca.patient.PatientInfoOrBuilder getPatientOrBuilder() {
      if (patientBuilder_ != null) {
        return patientBuilder_.getMessageOrBuilder();
      } else {
        return patient_ == null ?
            com.ca.patient.PatientInfo.getDefaultInstance() : patient_;
      }
    }
    /**
     * <code>.com.ca.patient.PatientInfo patient = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ca.patient.PatientInfo, com.ca.patient.PatientInfo.Builder, com.ca.patient.PatientInfoOrBuilder> 
        getPatientFieldBuilder() {
      if (patientBuilder_ == null) {
        patientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ca.patient.PatientInfo, com.ca.patient.PatientInfo.Builder, com.ca.patient.PatientInfoOrBuilder>(
                getPatient(),
                getParentForChildren(),
                isClean());
        patient_ = null;
      }
      return patientBuilder_;
    }

    private com.ca.patient.PracticeInfo practice_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ca.patient.PracticeInfo, com.ca.patient.PracticeInfo.Builder, com.ca.patient.PracticeInfoOrBuilder> practiceBuilder_;
    /**
     * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
     * @return Whether the practice field is set.
     */
    public boolean hasPractice() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
     * @return The practice.
     */
    public com.ca.patient.PracticeInfo getPractice() {
      if (practiceBuilder_ == null) {
        return practice_ == null ? com.ca.patient.PracticeInfo.getDefaultInstance() : practice_;
      } else {
        return practiceBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
     */
    public Builder setPractice(com.ca.patient.PracticeInfo value) {
      if (practiceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        practice_ = value;
      } else {
        practiceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
     */
    public Builder setPractice(
        com.ca.patient.PracticeInfo.Builder builderForValue) {
      if (practiceBuilder_ == null) {
        practice_ = builderForValue.build();
      } else {
        practiceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
     */
    public Builder mergePractice(com.ca.patient.PracticeInfo value) {
      if (practiceBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          practice_ != null &&
          practice_ != com.ca.patient.PracticeInfo.getDefaultInstance()) {
          getPracticeBuilder().mergeFrom(value);
        } else {
          practice_ = value;
        }
      } else {
        practiceBuilder_.mergeFrom(value);
      }
      if (practice_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
     */
    public Builder clearPractice() {
      bitField0_ = (bitField0_ & ~0x00000002);
      practice_ = null;
      if (practiceBuilder_ != null) {
        practiceBuilder_.dispose();
        practiceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
     */
    public com.ca.patient.PracticeInfo.Builder getPracticeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPracticeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
     */
    public com.ca.patient.PracticeInfoOrBuilder getPracticeOrBuilder() {
      if (practiceBuilder_ != null) {
        return practiceBuilder_.getMessageOrBuilder();
      } else {
        return practice_ == null ?
            com.ca.patient.PracticeInfo.getDefaultInstance() : practice_;
      }
    }
    /**
     * <code>.com.ca.patient.PracticeInfo practice = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ca.patient.PracticeInfo, com.ca.patient.PracticeInfo.Builder, com.ca.patient.PracticeInfoOrBuilder> 
        getPracticeFieldBuilder() {
      if (practiceBuilder_ == null) {
        practiceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ca.patient.PracticeInfo, com.ca.patient.PracticeInfo.Builder, com.ca.patient.PracticeInfoOrBuilder>(
                getPractice(),
                getParentForChildren(),
                isClean());
        practice_ = null;
      }
      return practiceBuilder_;
    }

    private java.lang.Object appointmentDateTime_ = "";
    /**
     * <code>string appointmentDateTime = 3;</code>
     * @return The appointmentDateTime.
     */
    public java.lang.String getAppointmentDateTime() {
      java.lang.Object ref = appointmentDateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appointmentDateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appointmentDateTime = 3;</code>
     * @return The bytes for appointmentDateTime.
     */
    public com.google.protobuf.ByteString
        getAppointmentDateTimeBytes() {
      java.lang.Object ref = appointmentDateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appointmentDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appointmentDateTime = 3;</code>
     * @param value The appointmentDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setAppointmentDateTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appointmentDateTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string appointmentDateTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppointmentDateTime() {
      appointmentDateTime_ = getDefaultInstance().getAppointmentDateTime();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string appointmentDateTime = 3;</code>
     * @param value The bytes for appointmentDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setAppointmentDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appointmentDateTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object appointmentCreationDateTime_ = "";
    /**
     * <code>string appointmentCreationDateTime = 4;</code>
     * @return The appointmentCreationDateTime.
     */
    public java.lang.String getAppointmentCreationDateTime() {
      java.lang.Object ref = appointmentCreationDateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appointmentCreationDateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appointmentCreationDateTime = 4;</code>
     * @return The bytes for appointmentCreationDateTime.
     */
    public com.google.protobuf.ByteString
        getAppointmentCreationDateTimeBytes() {
      java.lang.Object ref = appointmentCreationDateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appointmentCreationDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appointmentCreationDateTime = 4;</code>
     * @param value The appointmentCreationDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setAppointmentCreationDateTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appointmentCreationDateTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string appointmentCreationDateTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppointmentCreationDateTime() {
      appointmentCreationDateTime_ = getDefaultInstance().getAppointmentCreationDateTime();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string appointmentCreationDateTime = 4;</code>
     * @param value The bytes for appointmentCreationDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setAppointmentCreationDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appointmentCreationDateTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 5;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ca.patient.CreateAppointmentRequest)
  }

  // @@protoc_insertion_point(class_scope:com.ca.patient.CreateAppointmentRequest)
  private static final com.ca.patient.CreateAppointmentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ca.patient.CreateAppointmentRequest();
  }

  public static com.ca.patient.CreateAppointmentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateAppointmentRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateAppointmentRequest>() {
    @java.lang.Override
    public CreateAppointmentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateAppointmentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateAppointmentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ca.patient.CreateAppointmentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

