// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientService.proto

package com.ca.patient;

public interface GetAppointmentByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ca.patient.GetAppointmentByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 appointmentId = 1;</code>
   * @return The appointmentId.
   */
  long getAppointmentId();
}
