// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientService.proto

package com.ca.patient;

public interface GetPatientByRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ca.patient.GetPatientByRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 patientId = 1;</code>
   * @return The patientId.
   */
  long getPatientId();
}
