// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientService.proto

package com.ca.patient;

public interface PatientInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ca.patient.PatientInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 patientId = 1;</code>
   * @return The patientId.
   */
  long getPatientId();

  /**
   * <code>string firstName = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string dob = 4;</code>
   * @return The dob.
   */
  java.lang.String getDob();
  /**
   * <code>string dob = 4;</code>
   * @return The bytes for dob.
   */
  com.google.protobuf.ByteString
      getDobBytes();

  /**
   * <code>string gender = 5;</code>
   * @return The gender.
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 5;</code>
   * @return The bytes for gender.
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>string email = 6;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 6;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
