// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientService.proto

package com.ca.patient;

public final class PatientServiceOuterClass {
  private PatientServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ca_patient_PatientInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ca_patient_PatientInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ca_patient_PracticeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ca_patient_PracticeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ca_patient_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ca_patient_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ca_patient_CreatePatientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ca_patient_CreatePatientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ca_patient_GetPatientByRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ca_patient_GetPatientByRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ca_patient_Appointment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ca_patient_Appointment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ca_patient_CreateAppointmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ca_patient_CreateAppointmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ca_patient_GetAppointmentByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ca_patient_GetAppointmentByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ca_patient_GetAppointmentByPatientIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ca_patient_GetAppointmentByPatientIdRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PatientService.proto\022\016com.ca.patient\"q" +
      "\n\013PatientInfo\022\021\n\tpatientId\030\001 \001(\003\022\021\n\tfirs" +
      "tName\030\002 \001(\t\022\020\n\010lastName\030\003 \001(\t\022\013\n\003dob\030\004 \001" +
      "(\t\022\016\n\006gender\030\005 \001(\t\022\r\n\005email\030\006 \001(\t\"e\n\014Pra" +
      "cticeInfo\022\n\n\002id\030\001 \001(\003\022\024\n\014practiceName\030\002 " +
      "\001(\t\022\017\n\007address\030\003 \001(\t\022\023\n\013phoneNumber\030\004 \001(" +
      "\t\022\r\n\005email\030\005 \001(\t\"\311\001\n\007Address\022\n\n\002id\030\001 \001(\003" +
      "\022.\n\tpatientId\030\002 \001(\0132\033.com.ca.patient.Pat" +
      "ientInfo\0220\n\npracticeId\030\003 \001(\0132\034.com.ca.pa" +
      "tient.PracticeInfo\022\033\n\023appointmentDateTim" +
      "e\030\004 \001(\t\022#\n\033appointmentCreationDateTime\030\005" +
      " \001(\t\022\016\n\006status\030\006 \001(\t\"g\n\024CreatePatientReq" +
      "uest\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010lastName\030\002 \001(" +
      "\t\022\013\n\003dob\030\003 \001(\t\022\016\n\006gender\030\004 \001(\t\022\r\n\005email\030" +
      "\005 \001(\t\"(\n\023GetPatientByRequest\022\021\n\tpatientI" +
      "d\030\001 \001(\003\"\324\001\n\013Appointment\022\025\n\rappointmentId" +
      "\030\001 \001(\003\022,\n\007patient\030\002 \001(\0132\033.com.ca.patient" +
      ".PatientInfo\022.\n\010practice\030\003 \001(\0132\034.com.ca." +
      "patient.PracticeInfo\022\033\n\023appointmentDateT" +
      "ime\030\004 \001(\t\022#\n\033appointmentCreationDateTime" +
      "\030\005 \001(\t\022\016\n\006status\030\006 \001(\t\"\312\001\n\030CreateAppoint" +
      "mentRequest\022,\n\007patient\030\001 \001(\0132\033.com.ca.pa" +
      "tient.PatientInfo\022.\n\010practice\030\002 \001(\0132\034.co" +
      "m.ca.patient.PracticeInfo\022\033\n\023appointment" +
      "DateTime\030\003 \001(\t\022#\n\033appointmentCreationDat" +
      "eTime\030\004 \001(\t\022\016\n\006status\030\005 \001(\t\"2\n\031GetAppoin" +
      "tmentByIdRequest\022\025\n\rappointmentId\030\001 \001(\003\"" +
      "5\n GetAppointmentByPatientIdRequest\022\021\n\tp" +
      "atientId\030\001 \001(\0032\274\001\n\016PatientService\022T\n\016get" +
      "PatientById\022#.com.ca.patient.GetPatientB" +
      "yRequest\032\033.com.ca.patient.PatientInfo\"\000\022" +
      "T\n\rcreatePatient\022$.com.ca.patient.Create" +
      "PatientRequest\032\033.com.ca.patient.PatientI" +
      "nfo\"\0002\300\002\n\022AppointmentService\022^\n\022getAppoi" +
      "ntmentById\022).com.ca.patient.GetAppointme" +
      "ntByIdRequest\032\033.com.ca.patient.Appointme" +
      "nt\"\000\022l\n\031getAppointmentByPatientId\0220.com." +
      "ca.patient.GetAppointmentByPatientIdRequ" +
      "est\032\033.com.ca.patient.Appointment\"\000\022\\\n\021cr" +
      "eateAppointment\022(.com.ca.patient.CreateA" +
      "ppointmentRequest\032\033.com.ca.patient.Appoi" +
      "ntment\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ca_patient_PatientInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ca_patient_PatientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ca_patient_PatientInfo_descriptor,
        new java.lang.String[] { "PatientId", "FirstName", "LastName", "Dob", "Gender", "Email", });
    internal_static_com_ca_patient_PracticeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ca_patient_PracticeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ca_patient_PracticeInfo_descriptor,
        new java.lang.String[] { "Id", "PracticeName", "Address", "PhoneNumber", "Email", });
    internal_static_com_ca_patient_Address_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ca_patient_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ca_patient_Address_descriptor,
        new java.lang.String[] { "Id", "PatientId", "PracticeId", "AppointmentDateTime", "AppointmentCreationDateTime", "Status", });
    internal_static_com_ca_patient_CreatePatientRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ca_patient_CreatePatientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ca_patient_CreatePatientRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Dob", "Gender", "Email", });
    internal_static_com_ca_patient_GetPatientByRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ca_patient_GetPatientByRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ca_patient_GetPatientByRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_com_ca_patient_Appointment_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_ca_patient_Appointment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ca_patient_Appointment_descriptor,
        new java.lang.String[] { "AppointmentId", "Patient", "Practice", "AppointmentDateTime", "AppointmentCreationDateTime", "Status", });
    internal_static_com_ca_patient_CreateAppointmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_ca_patient_CreateAppointmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ca_patient_CreateAppointmentRequest_descriptor,
        new java.lang.String[] { "Patient", "Practice", "AppointmentDateTime", "AppointmentCreationDateTime", "Status", });
    internal_static_com_ca_patient_GetAppointmentByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_ca_patient_GetAppointmentByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ca_patient_GetAppointmentByIdRequest_descriptor,
        new java.lang.String[] { "AppointmentId", });
    internal_static_com_ca_patient_GetAppointmentByPatientIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_ca_patient_GetAppointmentByPatientIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ca_patient_GetAppointmentByPatientIdRequest_descriptor,
        new java.lang.String[] { "PatientId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
