// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientService.proto

package com.ca.patient;

public interface PracticeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ca.patient.PracticeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string practiceName = 2;</code>
   * @return The practiceName.
   */
  java.lang.String getPracticeName();
  /**
   * <code>string practiceName = 2;</code>
   * @return The bytes for practiceName.
   */
  com.google.protobuf.ByteString
      getPracticeNameBytes();

  /**
   * <code>string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string phoneNumber = 4;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phoneNumber = 4;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string email = 5;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 5;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
