// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: main/proto/schema.proto

package target

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookAuthorServiceClient is the client API for BookAuthorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookAuthorServiceClient interface {
	// unary
	// client will send one request and server will respond with one response.
	GetAuthor(ctx context.Context, in *Author, opts ...grpc.CallOption) (*Author, error)
	// sever streaming
	// client will send one request and server will send stream of response to the client.
	GetBooksByAuthor(ctx context.Context, in *Author, opts ...grpc.CallOption) (BookAuthorService_GetBooksByAuthorClient, error)
}

type bookAuthorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookAuthorServiceClient(cc grpc.ClientConnInterface) BookAuthorServiceClient {
	return &bookAuthorServiceClient{cc}
}

func (c *bookAuthorServiceClient) GetAuthor(ctx context.Context, in *Author, opts ...grpc.CallOption) (*Author, error) {
	out := new(Author)
	err := c.cc.Invoke(ctx, "/src.main.proto.BookAuthorService/getAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookAuthorServiceClient) GetBooksByAuthor(ctx context.Context, in *Author, opts ...grpc.CallOption) (BookAuthorService_GetBooksByAuthorClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookAuthorService_ServiceDesc.Streams[0], "/src.main.proto.BookAuthorService/getBooksByAuthor", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookAuthorServiceGetBooksByAuthorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookAuthorService_GetBooksByAuthorClient interface {
	Recv() (*Book, error)
	grpc.ClientStream
}

type bookAuthorServiceGetBooksByAuthorClient struct {
	grpc.ClientStream
}

func (x *bookAuthorServiceGetBooksByAuthorClient) Recv() (*Book, error) {
	m := new(Book)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookAuthorServiceServer is the server API for BookAuthorService service.
// All implementations must embed UnimplementedBookAuthorServiceServer
// for forward compatibility
type BookAuthorServiceServer interface {
	// unary
	// client will send one request and server will respond with one response.
	GetAuthor(context.Context, *Author) (*Author, error)
	// sever streaming
	// client will send one request and server will send stream of response to the client.
	GetBooksByAuthor(*Author, BookAuthorService_GetBooksByAuthorServer) error
	mustEmbedUnimplementedBookAuthorServiceServer()
}

// UnimplementedBookAuthorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookAuthorServiceServer struct {
}

func (UnimplementedBookAuthorServiceServer) GetAuthor(context.Context, *Author) (*Author, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthor not implemented")
}
func (UnimplementedBookAuthorServiceServer) GetBooksByAuthor(*Author, BookAuthorService_GetBooksByAuthorServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBooksByAuthor not implemented")
}
func (UnimplementedBookAuthorServiceServer) mustEmbedUnimplementedBookAuthorServiceServer() {}

// UnsafeBookAuthorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookAuthorServiceServer will
// result in compilation errors.
type UnsafeBookAuthorServiceServer interface {
	mustEmbedUnimplementedBookAuthorServiceServer()
}

func RegisterBookAuthorServiceServer(s grpc.ServiceRegistrar, srv BookAuthorServiceServer) {
	s.RegisterService(&BookAuthorService_ServiceDesc, srv)
}

func _BookAuthorService_GetAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Author)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookAuthorServiceServer).GetAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/src.main.proto.BookAuthorService/getAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookAuthorServiceServer).GetAuthor(ctx, req.(*Author))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookAuthorService_GetBooksByAuthor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Author)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookAuthorServiceServer).GetBooksByAuthor(m, &bookAuthorServiceGetBooksByAuthorServer{stream})
}

type BookAuthorService_GetBooksByAuthorServer interface {
	Send(*Book) error
	grpc.ServerStream
}

type bookAuthorServiceGetBooksByAuthorServer struct {
	grpc.ServerStream
}

func (x *bookAuthorServiceGetBooksByAuthorServer) Send(m *Book) error {
	return x.ServerStream.SendMsg(m)
}

// BookAuthorService_ServiceDesc is the grpc.ServiceDesc for BookAuthorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookAuthorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "src.main.proto.BookAuthorService",
	HandlerType: (*BookAuthorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getAuthor",
			Handler:    _BookAuthorService_GetAuthor_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getBooksByAuthor",
			Handler:       _BookAuthorService_GetBooksByAuthor_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "main/proto/schema.proto",
}
